### ISSUE TITLE
Missing automatic provisioning at scale with Azure IoT Edge using EST protocol 

### ISSUE THREAD

**Issue by senssei** [markeytos/AzureIoTSamples#5]
Hi, 

based on samples I was not able to use the native certificate management feature of Azure IoT edge - EST endpoint implementation 

https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-configure-est-server?view=iotedge-1.5

Is this possible with EZCA?

**Comment by igalfsg** [comment]
Hi Unfortunately we currently do not, most of our customers use our [provisioning APIs](https://www.keytos.io/docs/azure-pki/azure-iot-hub/certificate-based-authentication/) to create devices, but thanks for bringing this issue to our attention, we will implement it in the coming weeks and update this thread issue when implemented

**Comment by igalfsg** [comment]
Hi this is now possible with EZCA, we have also created a sample for how to issue EST certificates in code: https://github.com/markeytos/EST-Certificate-Client
